---
title: "Conceptual Questions"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

1.  If your working directory is `myfolder/homework/`, what relative path would you specify to get the file located at `myfolder/MyData.csv`?

    > `../MyData.csv`

2.  What are the major benefits of using R projects?

    > By using R Projects, the separation of associated documents, data sources, and other files for each project is maintained. Each project also serves as a working directory, so sharing and collaborating with others is easier.

3.  What is git and what is github?

    > Git is a version control software and Github is a tool where Git is hosted.

4.  What are the two main differences between a tibble and a data.frame?

    > Tibbles print in a more efficient and interpret-able way than data frames. They show the first couple of rows and columns and a count of the number of total observations and columns. Tibbles are also more strict and require consistent data types than data frames.

5.  Rewrite the following nested function call using BaseR’s chaining operator:

    `arrange(filter(select(as_tibble(iris), starts_with("Petal"), Species), Petal.Length <1.55), Species)`

    > `iris |>`
    >
    > `as_tibble() |>`
    >
    > `select(starts_with("Petal"), Species) |>`
    >
    > `filter(Petal.Length <1.55) |>`
    >
    > `arrange(Species)`
