---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse) 
glass <- read_csv("https://www4.stat.ncsu.edu/online/datasets/glass.data",col_names = c('Id','RI','Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type_of_Glass'))
glass
```

```{r}
glass_mutate <- glass |>
  mutate(Type_of_Glass = ifelse(Type_of_Glass== 1, 
                             'building_windows_float_processed', 
                             ifelse(Type_of_Glass== 2, 
                                    'building_windows_non_float_processed', 
                                    ifelse(Type_of_Glass == 3, 
                                           'vehicle_windows_float_processed', 
                                           ifelse(Type_of_Glass==4, 
                                                  'vehicle_windows_non_float_processed',
                                                  ifelse(Type_of_Glass==5,
                                                         'containers',
                                                         ifelse(Type_of_Glass==6,
                                                                'tableware',
                                                                'headlamps'))))))) |>
  filter(Fe < 0.2 & Type_of_Glass %in% c('tableware', 'headlamps'))
glass_mutate

```

```{r}
yeast <- read_table('https://www4.stat.ncsu.edu/online/datasets/yeast.data', col_names = c('seq_name', 'mcg', 'gvh','alm','mit','erl','pox','vac','nuc','class'), show_col_types = FALSE)
yeast
```

```{r}
yeast |>
  select(mcg, gvh, alm, mit, erl, pox, vac, class) |>
  mutate(across(c(mcg, gvh, alm, mit, erl, pox, vac), 
                        list(mean=mean,median=median), na.rm=TRUE,
                        .names = '{col}_{fn}')) |>
  group_by(class)
```
